### ISSUE TITLE
Update to angular 11

### ISSUE THREAD

**Issue by PetersonFonsec** [nncl/ngx-datepicker#40]
Não esta sendo possível instalar a lib, acredito que seja devido a versão que eu utilizo no projeto não ser a mesma que a usada pela lib. Segue print do erro.

![Screen Shot 2021-06-29 at 15 51 33](https://user-images.githubusercontent.com/41239234/123851696-e378e100-d8f1-11eb-8747-0d31c6cfefc1.png)

**Comment by nncl** [comment]
Olá @PetersonFonsec. 

De fato o problema está relacionado à versão do Angular suportada pela lib - que é a 10 - estar desatualizada.

Ainda essa semana atualizarei para suportar a versão mais atual do Angular, que é a ~12.

**EN**:
In fact, the problem is related to its current supported version, which is v10.

This week I'll update it to support the latest one, which is v12.

**Comment by nncl** [comment]
@PetersonFonsec desculpe a demora. Realizei a publicação da versão [1.9.4](https://github.com/nncl/ngx-datepicker/releases/tag/v1.9.4), que foi testada com um projeto do 0 na última versão do Angular - data atual.
